### ISSUE TITLE
Fatal error in admin dashboard

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#811]
```
[Fri Mar 29 11:32:07.077215 2019] [php7:notice] [pid 52130] [client ::1:56669] PHP Fatal error:  Uncaught mysqli_sql_exception: Illegal argument to a regular expression. in /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php:159\nStack trace:\n#0 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php(159): mysqli_query(Object(mysqli), 'SELECT `attribu...')\n#1 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php(276): iaDb->query('SELECT `attribu...')\n#2 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php(242): iaDb->getAll('SELECT `attribu...')\n#3 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php(547): iaDb->_get('all', Array, ' WHERE `pages` ...', NULL, NULL)\n#4 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.view.php(1368): iaDb->all(Array, '`pages` REGEXP(...', NULL, NULL, 'admin_actions')\n#5 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.view.php(926): iaView->_getAdminToolbarActions()\n#6 /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core in /Users/vbezruchkin/projects/www/subrion/includes/classes/ia.core.mysqli.php on line 159, referer: http://localhost/subrion/panel/modules/
```

@Batry please check this asap. The system is unusable now. 

Thanks

**Comment by vbezruchkin** [comment]
> mysql  Ver 8.0.15 for osx10.14 on x86_64 (Homebrew)'

Related to #802

**Comment by vbezruchkin** [comment]
The Spencer library supports word-beginning and word-end boundary markers ([[:<:]] and [[:>:]] notation). ICU does not. For ICU, you can use \b to match word boundaries; double the backslash because MySQL interprets it as the escape character within strings.

**Comment by ghost** [comment]
Looks like the functionality is now broken. There are no action buttons in Admin Panel anymore.
