### ISSUE TITLE
Subrion 4.2.1 Installation - I only see a blank page only in admin panel 

### ISSUE THREAD

**Issue by Ghost173** [intelliants/subrion#851]
```
i install my local host then i try to access admin panel i get this error 

`Fatal error: Uncaught mysqli_sql_exception: Illegal argument to a regular expression. in /var/www/html/sub1/includes/classes/ia.core.mysqli.php:159 Stack trace:
 #0 /var/www/html/sub1/includes/classes/ia.core.mysqli.php(159): mysqli_query(Object(mysqli), 'SELECT `attribu...') `
`#1 /var/www/html/sub1/includes/classes/ia.core.mysqli.php(276): iaDb->query('SELECT `attribu...') `#2 /var/www/html/sub1/includes/classes/ia.core.mysqli.php(242): iaDb->getAll('SELECT `attribu...') #3 /var/www/html/sub1/includes/classes/ia.core.mysqli.php(547): iaDb->_get('all', Array, ' WHERE `pages` ...', NULL, NULL) #4 /var/www/html/sub1/includes/classes/ia.core.view.php(1368): iaDb->all(Array, '`pages` REGEXP(...', NULL, NULL, 'admin_actions') #5 /var/www/html/sub1/includes/classes/ia.core.view.php(926): iaView->_getAdminToolbarActions() #6 /var/www/html/sub1/includes/classes/ia.core.php(161): iaView->output() #7 /var/www/html/sub1/index.php(123): iaCore->init() #8 {main} thrown in /var/www/html/sub1/includes/classes/ia.core.mysqli.php on line 159


```

PHP - PHP 7.3.11-0ubuntu0.19.10.1
MYSQL - mysql  Ver 8.0.18-0ubuntu0.19.10.1 for Linux on x86_64 ((Ubuntu))

when i try to access admin panel (http://localhost/sub1/panel/) i got balnk page but front page is working fine

**Comment by 4unkur** [comment]
This issue has been already resolved here: https://github.com/intelliants/subrion/issues/811   
We haven't released the patch yet, so please use Github version of the script (develop branch)
