### ISSUE TITLE
Cannot view the landing paage

### ISSUE THREAD

**Issue by ratheesh0203** [intelliants/subrion#876]
Fatal error: Uncaught Error: Call to undefined method iaCore::factoryPlugin() in /opt/lampp/htdocs/subrion/includes/classes/ia.core.php(709) : eval()'d code:1 Stack trace: #0 /opt/lampp/htdocs/subrion/includes/classes/ia.core.php(709): eval() #1 /opt/lampp/htdocs/subrion/includes/classes/ia.core.view.php(968): iaCore->startHook('phpCoreDisplayB...') #2 /opt/lampp/htdocs/subrion/includes/classes/ia.core.php(161): iaView->output() #3 /opt/lampp/htdocs/subrion/index.php(123): iaCore->init() #4 {main} thrown in /opt/lampp/htdocs/subrion/includes/classes/ia.core.php(709) : eval()'d code on line 1

**Comment by vbezruchkin** [comment]
Hi

Looks like you tried to install an incompatible plugin. Probably it's from the obsolete version and has some incompatible hooks. The only way is to disable hooks related to this plugin, and then uninstall the plugin.

**Comment by ratheesh0203** [comment]
@vbezruchkin you're correct but i can't remove that hook...

**Comment by vbezruchkin** [comment]
Just disable it in hooks table in phpMyAdmin or any other tool for db.
